import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Projects.module.css'
import Layout from '../components/Layout'
import ProjectsCardLeft from '../components/ProjectsCardLeft'
import ProjectsCardRight from '../components/ProjectsCardRight'



export default function Home() {

    const text1 = "Uno dei primi progetti realizzati, basato sulla challenge di Frontend Mentor. Il progetto è stato implementato utilizzando HTML,CSS,Javascript e una delle caratteristiche principali di questo progetto è lo stile responsive in modo da adattare il layout della pagina sulla base del dispositivo dell'utente."
    const img1 = "/images/loopstudiosDesign.jpg";
    const title1 = "LOOPSTUDIOS";

    const text2 = "Uno dei primi progetti realizzati, basato sulla challenge di Frontend Mentor. Il progetto è stato implementato utilizzando HTML,CSS,Javascript e una delle caratteristiche principali di questo progetto è lo stile responsive in modo da adattare il layout della pagina sulla base del dispositivo dell'utente."
    const img2 = "/images/dashboardDesign.png";
    const title2 = "SOCIAL DASHBOARD";

    const text3 = "Uno dei primi progetti realizzati, basato sulla challenge di Frontend Mentor. Il progetto è stato implementato utilizzando HTML,CSS,Javascript e una delle caratteristiche principali di questo progetto è lo stile responsive in modo da adattare il layout della pagina sulla base del dispositivo dell'utente."
    const img3 = "/images/iofDesign.png";
    const title3 = "IoF";

    return (
    <Layout>
        <Head>
            <title>Portfolio - Antonio Bertoni - Progetti</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.main}>
            <ProjectsCardLeft text={text1} img={img1} num={"01"} title={title1}/>
            <ProjectsCardRight text={text2} img={img2} num={"02"} title={title2}/>
            <ProjectsCardLeft text={text3} img={img3} num={"03"} title={title3}/>
        </div>
    </Layout>
    )
}

/* Contribuzione nel footer: <a href="https://www.flaticon.com/free-icons/web-development" title="web development icons">Web development icons created by Freepik - Flaticon</a> */
